-- Milestones lay out the path to a project's outcome (#161). Tasks
-- (project_actions) may belong to one milestone of the same project; tasks
-- without one keep working as before, so existing rows need no migration.

create table if not exists public.project_milestones (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete restrict,
  title text not null check (char_length(title) between 1 and 240),
  due_on date,
  sort_order integer not null default 0,
  status text not null default 'open' check (status in ('open', 'done')),
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (status = 'done' and completed_at is not null) or
    (status = 'open' and completed_at is null)
  ),
  -- Lets project_actions reference (project_id, id) so a task can only join
  -- a milestone of its own project.
  unique (project_id, id)
);

create index if not exists project_milestones_project_order_idx
  on public.project_milestones (project_id, sort_order, id);

alter table public.project_milestones enable row level security;
revoke all on table public.project_milestones from anon, authenticated;
grant select, insert, update, delete on table public.project_milestones to service_role;

comment on table public.project_milestones is
  'Ordered milestones on the way to a project''s outcome. Tasks link to them through project_actions.milestone_id.';

alter table public.project_actions
  add column if not exists milestone_id bigint;

alter table public.project_actions
  drop constraint if exists project_actions_milestone_same_project_fkey;
alter table public.project_actions
  add constraint project_actions_milestone_same_project_fkey
  foreign key (project_id, milestone_id)
  references public.project_milestones (project_id, id)
  on delete restrict;

create index if not exists project_actions_milestone_id_idx
  on public.project_actions (milestone_id);

comment on column public.project_actions.milestone_id is
  'Milestone of the same project this task belongs to. Null when the task has no milestone.';

-- p_operation:
--   create            new milestone at the end (p_milestone_id null; locks on p_project_updated_at)
--   edit              title / due_on
--   complete / reopen status done <-> open
--   move_up / move_down  swap with the neighbouring milestone
--   delete            remove the milestone; its tasks stay, without a milestone
create or replace function public.update_project_milestone(
  p_project_id bigint,
  p_project_updated_at timestamptz,
  p_milestone_id bigint,
  p_milestone_updated_at timestamptz,
  p_operation text,
  p_title text,
  p_due_on date
)
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_project public.projects%rowtype;
  v_milestone public.project_milestones%rowtype;
  v_neighbour public.project_milestones%rowtype;
  v_milestone_id bigint;
begin
  select * into v_project
  from public.projects
  where id = p_project_id
  for update;
  if not found then
    raise exception 'PROJECT_CONFLICT';
  end if;
  if v_project.status in ('completed', 'dropped') then
    raise exception 'PROJECT_NOT_OPEN';
  end if;

  if p_operation = 'create' then
    if v_project.updated_at <> p_project_updated_at then
      raise exception 'PROJECT_CONFLICT';
    end if;
    if nullif(btrim(p_title), '') is null then
      raise exception 'MILESTONE_TITLE_REQUIRED';
    end if;
    insert into public.project_milestones (project_id, title, due_on, sort_order)
    values (
      p_project_id,
      btrim(p_title),
      p_due_on,
      coalesce((select max(sort_order) from public.project_milestones where project_id = p_project_id), 0) + 1
    )
    returning id into v_milestone_id;
  else
    select * into v_milestone
    from public.project_milestones
    where id = p_milestone_id and project_id = p_project_id and updated_at = p_milestone_updated_at
    for update;
    if not found then
      raise exception 'MILESTONE_CONFLICT';
    end if;
    v_milestone_id := v_milestone.id;

    if p_operation = 'edit' then
      if nullif(btrim(p_title), '') is null then
        raise exception 'MILESTONE_TITLE_REQUIRED';
      end if;
      update public.project_milestones
      set title = btrim(p_title), due_on = p_due_on, updated_at = now()
      where id = v_milestone.id;
    elsif p_operation = 'complete' then
      update public.project_milestones
      set status = 'done', completed_at = now(), updated_at = now()
      where id = v_milestone.id and status = 'open';
    elsif p_operation = 'reopen' then
      update public.project_milestones
      set status = 'open', completed_at = null, updated_at = now()
      where id = v_milestone.id and status = 'done';
    elsif p_operation in ('move_up', 'move_down') then
      -- Renumber first so equal or missing positions never block a swap.
      with ranked as (
        select id, row_number() over (order by sort_order asc, id asc)::integer as position
        from public.project_milestones
        where project_id = p_project_id
      )
      update public.project_milestones as milestone
      set sort_order = ranked.position
      from ranked
      where milestone.id = ranked.id and milestone.sort_order <> ranked.position;

      select * into v_milestone from public.project_milestones where id = v_milestone_id;
      select * into v_neighbour
      from public.project_milestones
      where project_id = p_project_id
        and sort_order = v_milestone.sort_order + case when p_operation = 'move_up' then -1 else 1 end;
      if not found then
        raise exception 'MILESTONE_MOVE_OUT_OF_RANGE';
      end if;
      update public.project_milestones set sort_order = v_neighbour.sort_order, updated_at = now() where id = v_milestone.id;
      update public.project_milestones set sort_order = v_milestone.sort_order, updated_at = now() where id = v_neighbour.id;
    elsif p_operation = 'delete' then
      update public.project_actions
      set milestone_id = null, updated_at = now()
      where milestone_id = v_milestone.id;
      delete from public.project_milestones where id = v_milestone.id;
    else
      raise exception 'MILESTONE_OPERATION_INVALID';
    end if;
  end if;

  update public.projects
  set updated_at = now()
  where id = p_project_id;

  return v_milestone_id;
end;
$$;

-- Adds several queued tasks at the end of the queue in one transaction, for
-- pasting a planned path (one task per line on the screen).
create or replace function public.add_project_queued_actions(
  p_project_id bigint,
  p_project_updated_at timestamptz,
  p_contents text[],
  p_milestone_id bigint
)
returns integer
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_project public.projects%rowtype;
  v_position integer;
  v_content text;
  v_count integer := 0;
begin
  select * into v_project
  from public.projects
  where id = p_project_id and updated_at = p_project_updated_at
  for update;
  if not found then
    raise exception 'PROJECT_CONFLICT';
  end if;
  if v_project.status <> 'active' then
    raise exception 'PROJECT_NOT_ACTIVE';
  end if;
  if coalesce(array_length(p_contents, 1), 0) not between 1 and 50 then
    raise exception 'ACTIONS_COUNT_INVALID';
  end if;
  if p_milestone_id is not null and not exists (
    select 1 from public.project_milestones where id = p_milestone_id and project_id = p_project_id
  ) then
    raise exception 'ACTION_MILESTONE_INVALID';
  end if;

  select coalesce(max(sort_order), 0) into v_position
  from public.project_actions
  where project_id = p_project_id and status = 'queued';

  foreach v_content in array p_contents loop
    if nullif(btrim(v_content), '') is null then
      raise exception 'ACTION_CONTENT_REQUIRED';
    end if;
    v_position := v_position + 1;
    insert into public.project_actions (project_id, content, status, sort_order, milestone_id)
    values (p_project_id, btrim(v_content), 'queued', v_position, p_milestone_id);
    v_count := v_count + 1;
  end loop;

  update public.projects
  set updated_at = now()
  where id = p_project_id;

  return v_count;
end;
$$;

-- update_project_action gains p_milestone_id: "edit" now also sets the
-- task's milestone, and move_up / move_down swap within the same milestone
-- (the order the screen shows them in). The old six-argument version is
-- dropped so PostgREST never sees two candidates.
drop function if exists public.update_project_action(bigint, timestamptz, text, text, date, date);

create or replace function public.update_project_action(
  p_action_id bigint,
  p_action_updated_at timestamptz,
  p_operation text,
  p_content text,
  p_due_on date,
  p_start_on date,
  p_milestone_id bigint default null
)
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_project_id bigint;
  v_action public.project_actions%rowtype;
  v_project public.projects%rowtype;
  v_neighbour public.project_actions%rowtype;
begin
  select project_id into v_project_id
  from public.project_actions
  where id = p_action_id;
  if not found then
    raise exception 'ACTION_CONFLICT';
  end if;

  -- Lock every open action of the project in id order before the project row,
  -- so this never waits on the project while holding an action that
  -- resolve_project_next_action (action -> project) needs.
  perform 1
  from public.project_actions
  where project_id = v_project_id and status in ('next', 'queued', 'waiting')
  order by id
  for update;

  select * into v_project
  from public.projects
  where id = v_project_id
  for update;

  select * into v_action
  from public.project_actions
  where id = p_action_id and updated_at = p_action_updated_at;
  if not found then
    raise exception 'ACTION_CONFLICT';
  end if;
  if v_project.status in ('completed', 'dropped') then
    raise exception 'PROJECT_NOT_OPEN';
  end if;

  if p_operation = 'edit' then
    if v_action.status not in ('next', 'queued', 'waiting') then
      raise exception 'ACTION_CONFLICT';
    end if;
    if nullif(btrim(p_content), '') is null then
      raise exception 'ACTION_CONTENT_REQUIRED';
    end if;
    if p_start_on is not null and p_due_on is not null and p_start_on > p_due_on then
      raise exception 'ACTION_DATES_INVALID';
    end if;
    if p_milestone_id is not null and not exists (
      select 1 from public.project_milestones where id = p_milestone_id and project_id = v_project.id
    ) then
      raise exception 'ACTION_MILESTONE_INVALID';
    end if;
    update public.project_actions
    set content = btrim(p_content), due_on = p_due_on, start_on = p_start_on,
        milestone_id = p_milestone_id, updated_at = now()
    where id = v_action.id;

  elsif p_operation in ('complete', 'cancel') then
    if v_action.status not in ('queued', 'waiting') then
      raise exception 'ACTION_CONFLICT';
    end if;
    update public.project_actions
    set status = case when p_operation = 'complete' then 'done' else 'cancelled' end,
        completed_at = case when p_operation = 'complete' then now() else null end,
        waiting_for = null,
        sort_order = null,
        updated_at = now()
    where id = v_action.id;

  elsif p_operation = 'pin' then
    if v_action.status <> 'queued' then
      raise exception 'ACTION_CONFLICT';
    end if;
    if v_project.status <> 'active' then
      raise exception 'PROJECT_NOT_ACTIVE';
    end if;
    update public.project_actions
    set status = 'queued', sort_order = 0, updated_at = now()
    where project_id = v_project.id and status = 'next';
    update public.project_actions
    set status = 'next', sort_order = null, updated_at = now()
    where id = v_action.id;

  elsif p_operation in ('move_up', 'move_down') then
    if v_action.status <> 'queued' then
      raise exception 'ACTION_CONFLICT';
    end if;
    with ranked as (
      select id, row_number() over (order by sort_order asc nulls last, created_at asc, id asc)::integer as position
      from public.project_actions
      where project_id = v_project.id and status = 'queued'
    )
    update public.project_actions as action
    set sort_order = ranked.position
    from ranked
    where action.id = ranked.id and action.sort_order is distinct from ranked.position;

    select * into v_action from public.project_actions where id = p_action_id;
    -- The neighbour is the closest queued task of the same milestone.
    if p_operation = 'move_up' then
      select * into v_neighbour
      from public.project_actions
      where project_id = v_project.id and status = 'queued'
        and milestone_id is not distinct from v_action.milestone_id
        and sort_order < v_action.sort_order
      order by sort_order desc
      limit 1;
    else
      select * into v_neighbour
      from public.project_actions
      where project_id = v_project.id and status = 'queued'
        and milestone_id is not distinct from v_action.milestone_id
        and sort_order > v_action.sort_order
      order by sort_order asc
      limit 1;
    end if;
    if not found then
      raise exception 'ACTION_MOVE_OUT_OF_RANGE';
    end if;
    update public.project_actions set sort_order = v_neighbour.sort_order, updated_at = now() where id = v_action.id;
    update public.project_actions set sort_order = v_action.sort_order, updated_at = now() where id = v_neighbour.id;

  else
    raise exception 'ACTION_OPERATION_INVALID';
  end if;

  update public.projects
  set updated_at = now()
  where id = v_project.id;

  return v_project.id;
end;
$$;

revoke all on function public.update_project_milestone(bigint, timestamptz, bigint, timestamptz, text, text, date) from public, anon, authenticated;
grant execute on function public.update_project_milestone(bigint, timestamptz, bigint, timestamptz, text, text, date) to service_role;
revoke all on function public.add_project_queued_actions(bigint, timestamptz, text[], bigint) from public, anon, authenticated;
grant execute on function public.add_project_queued_actions(bigint, timestamptz, text[], bigint) to service_role;
revoke all on function public.update_project_action(bigint, timestamptz, text, text, date, date, bigint) from public, anon, authenticated;
grant execute on function public.update_project_action(bigint, timestamptz, text, text, date, date, bigint) to service_role;
