-- Wants remain the source idea. Each destination is recorded separately
-- so one Want can become, for example, a research calendar plan and later a
-- Knowledge entry or Writing topic.

create table if not exists public.want_routes (
  id bigint generated by default as identity primary key,
  want_id bigint not null references public.wants(id) on delete restrict,
  intent text not null check (intent in ('act', 'continue', 'explore', 'keep', 'discard')),
  destination text not null check (destination in ('calendar', 'github', 'writing', 'habit', 'knowledge', 'focus', 'journal', 'archive')),
  status text not null default 'planned' check (status in ('planned', 'created', 'failed', 'cancelled')),
  title text not null check (char_length(title) between 1 and 240),
  detail text check (detail is null or char_length(detail) <= 2000),
  cadence text check (cadence is null or cadence in ('daily', 'weekdays', 'weekly', 'flexible')),
  target_id text,
  target_url text,
  error_code text,
  idempotency_key uuid not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (intent = 'act' and destination in ('calendar', 'github')) or
    (intent = 'continue' and destination = 'habit') or
    (intent = 'explore' and destination in ('calendar', 'knowledge', 'writing')) or
    (intent = 'keep' and destination in ('focus', 'journal', 'archive')) or
    (intent = 'discard' and destination = 'archive')
  ),
  check (
    (destination = 'habit' and cadence is not null) or
    (destination <> 'habit' and cadence is null)
  ),
  check (status <> 'created' or target_id is not null)
);

create index if not exists want_routes_want_id_created_at_idx
  on public.want_routes (want_id, created_at desc);

create table if not exists public.writing_topics (
  id bigint generated by default as identity primary key,
  source_route_id bigint not null unique references public.want_routes(id) on delete restrict,
  source_want_id bigint not null references public.wants(id) on delete restrict,
  title text not null check (char_length(title) between 1 and 240),
  question text check (question is null or char_length(question) <= 2000),
  notes text,
  status text not null default 'candidate' check (status in ('candidate', 'researching', 'outlining', 'drafting', 'completed', 'on_hold', 'archived')),
  draft_url text,
  next_review_on date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.habits (
  id bigint generated by default as identity primary key,
  source_route_id bigint not null unique references public.want_routes(id) on delete restrict,
  source_want_id bigint not null references public.wants(id) on delete restrict,
  name text not null check (char_length(name) between 1 and 240),
  purpose text check (purpose is null or char_length(purpose) <= 2000),
  cadence text not null check (cadence in ('daily', 'weekdays', 'weekly', 'flexible')),
  status text not null default 'active' check (status in ('active', 'paused', 'archived')),
  calendar_event_id text,
  calendar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.habit_logs (
  id bigint generated by default as identity primary key,
  habit_id bigint not null references public.habits(id) on delete restrict,
  practiced_on date not null,
  note text check (note is null or char_length(note) <= 2000),
  created_at timestamptz not null default now(),
  unique (habit_id, practiced_on)
);

create table if not exists public.focus_items (
  id bigint generated by default as identity primary key,
  source_route_id bigint not null unique references public.want_routes(id) on delete restrict,
  source_want_id bigint not null references public.wants(id) on delete restrict,
  content text not null check (char_length(content) between 1 and 240),
  note text check (note is null or char_length(note) <= 2000),
  status text not null default 'active' check (status in ('active', 'archived')),
  sort_order integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.want_routes enable row level security;
alter table public.writing_topics enable row level security;
alter table public.habits enable row level security;
alter table public.habit_logs enable row level security;
alter table public.focus_items enable row level security;

comment on table public.want_routes is 'Auditable routing results from Wants to their canonical management systems.';
comment on column public.want_routes.status is 'planned means no canonical target has been created yet; created means target_id was verified.';
