-- Calendar routes describe where an idea was organized. Scheduled actions
-- separately track whether that planned action was actually carried out.

create table if not exists public.scheduled_actions (
  id bigint generated by default as identity primary key,
  source_route_id bigint not null unique references public.want_routes(id) on delete restrict,
  status text not null default 'pending' check (status in ('pending', 'completed', 'skipped')),
  current_schedule jsonb not null,
  completed_at timestamptz,
  note text check (note is null or char_length(note) <= 2000),
  reschedule_count integer not null default 0 check (reschedule_count >= 0),
  last_calendar_sync_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    jsonb_typeof(current_schedule) = 'object' and
    current_schedule ?& array['allDay', 'date', 'startTime', 'endTime', 'timeZone'] and
    current_schedule ->> 'timeZone' = 'Asia/Tokyo'
  ),
  check (
    (status = 'completed' and completed_at is not null) or
    (status <> 'completed' and completed_at is null)
  )
);

create table if not exists public.scheduled_action_schedule_history (
  id bigint generated by default as identity primary key,
  scheduled_action_id bigint not null references public.scheduled_actions(id) on delete restrict,
  previous_schedule jsonb not null,
  next_schedule jsonb not null,
  changed_at timestamptz not null default now(),
  check (previous_schedule <> next_schedule)
);

create index if not exists scheduled_actions_status_updated_at_idx
  on public.scheduled_actions (status, updated_at desc);

create index if not exists scheduled_action_history_action_changed_idx
  on public.scheduled_action_schedule_history (scheduled_action_id, changed_at desc);

alter table public.scheduled_actions enable row level security;
alter table public.scheduled_action_schedule_history enable row level security;

create or replace function public.ensure_scheduled_action_after_calendar_route()
returns trigger
language plpgsql
as $$
begin
  if new.destination = 'calendar'
     and new.status = 'created'
     and new.target_id is not null
     and jsonb_typeof(new.destination_data -> 'calendar') = 'object' then
    insert into public.scheduled_actions (source_route_id, current_schedule)
    values (new.id, new.destination_data -> 'calendar')
    on conflict (source_route_id) do nothing;
  end if;
  return new;
end;
$$;

drop trigger if exists ensure_scheduled_action_after_calendar_route on public.want_routes;

create trigger ensure_scheduled_action_after_calendar_route
after insert or update on public.want_routes
for each row
execute function public.ensure_scheduled_action_after_calendar_route();

-- Existing successfully-created Calendar routes enter the new ToDo queue once.
insert into public.scheduled_actions (source_route_id, current_schedule, created_at, updated_at)
select route.id, route.destination_data -> 'calendar', route.created_at, route.updated_at
  from public.want_routes as route
 where route.destination = 'calendar'
   and route.status = 'created'
   and route.target_id is not null
   and jsonb_typeof(route.destination_data -> 'calendar') = 'object'
on conflict (source_route_id) do nothing;

comment on table public.scheduled_actions is
  'Execution state for actions scheduled in Google Calendar. Calendar remains the schedule source of truth.';
comment on table public.scheduled_action_schedule_history is
  'Successful Dashboard-initiated Calendar reschedules for a scheduled action.';
