-- 定期家計簿: ルール、生成履歴、冪等な日次生成、Supabase Cron。
-- SQL Editorで一度実行する。既存expenses行は変更しない。

create table if not exists public.recurring_expenses (
  id bigint generated by default as identity primary key,
  source_expense_id bigint references public.expenses(id) on delete restrict,
  template_rule_id bigint references public.recurring_expenses(id) on delete set null,
  frequency text not null check (frequency in ('daily', 'weekly', 'monthly')),
  interval_count integer not null default 1 check (interval_count between 1 and 365),
  day_of_month smallint not null check (day_of_month between 1 and 31),
  start_date date not null,
  end_date date,
  next_run_date date not null,
  active boolean not null default true,
  amount bigint not null check (amount <> 0),
  title text not null check (length(btrim(title)) between 1 and 200),
  category text not null references public.budget_categories(name) on update cascade on delete restrict,
  payer text,
  memo text,
  last_generated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint recurring_expenses_dates_valid check (end_date is null or end_date >= start_date)
);

-- 旧仕様では9月1日の明細が必須かつ一意だった。既存値は監査用に残し、新規ルールは既存ルールをテンプレートにする。
alter table public.recurring_expenses alter column source_expense_id drop not null;
alter table public.recurring_expenses
  add column if not exists template_rule_id bigint references public.recurring_expenses(id) on delete set null;

create table if not exists public.recurring_expense_occurrences (
  rule_id bigint not null references public.recurring_expenses(id) on delete cascade,
  scheduled_for date not null,
  expense_id bigint not null references public.expenses(id) on delete restrict,
  created_at timestamptz not null default now(),
  primary key (rule_id, scheduled_for),
  unique (expense_id)
);

alter table public.recurring_expenses enable row level security;
alter table public.recurring_expense_occurrences enable row level security;
revoke all on public.recurring_expenses from anon, authenticated;
revoke all on public.recurring_expense_occurrences from anon, authenticated;
grant select, insert, update, delete on public.recurring_expenses to service_role;
grant select, insert, update, delete on public.recurring_expense_occurrences to service_role;
grant usage, select on sequence public.recurring_expenses_id_seq to service_role;

create or replace function public.next_recurring_date(p_date date, p_frequency text, p_interval integer, p_day_of_month integer)
returns date language sql immutable strict as $$
  select case p_frequency
    when 'daily' then p_date + p_interval
    when 'weekly' then p_date + (7 * p_interval)
    when 'monthly' then (
      date_trunc('month', p_date + make_interval(months => p_interval))::date
      + least(
          p_day_of_month,
          extract(day from (date_trunc('month', p_date + make_interval(months => p_interval)) + interval '1 month - 1 day'))::integer
        ) - 1
    )::date
  end
$$;

create or replace function public.create_recurring_expense_rule(
  p_template_rule_id bigint,
  p_start_date date,
  p_frequency text,
  p_interval_count integer,
  p_end_date date,
  p_amount bigint,
  p_title text,
  p_category text,
  p_payer text,
  p_memo text
) returns setof public.recurring_expenses
language plpgsql security definer set search_path = public as $$
declare
  template_row public.recurring_expenses%rowtype;
  created_rule public.recurring_expenses%rowtype;
begin
  if p_frequency not in ('daily', 'weekly', 'monthly') or p_interval_count not between 1 and 365 then
    raise exception 'invalid recurring schedule';
  end if;
  if p_start_date is null or p_amount = 0 or length(btrim(p_title)) not between 1 and 200 then
    raise exception 'invalid recurring values';
  end if;
  select * into strict template_row from public.recurring_expenses where id = p_template_rule_id;
  if p_end_date is not null and p_end_date < p_start_date then
    raise exception 'end date precedes start date';
  end if;
  insert into public.recurring_expenses (
    template_rule_id, frequency, interval_count, day_of_month, start_date, end_date, next_run_date,
    amount, title, category, payer, memo
  ) values (
    template_row.id, p_frequency, p_interval_count, extract(day from p_start_date)::integer, p_start_date, p_end_date, p_start_date,
    p_amount, btrim(p_title), btrim(p_category), nullif(btrim(p_payer), ''), nullif(btrim(p_memo), '')
  ) returning * into created_rule;
  return next created_rule;
end
$$;

create or replace function public.materialize_recurring_expenses(p_through_date date default (now() at time zone 'Asia/Tokyo')::date)
returns integer language plpgsql security definer set search_path = public as $$
declare
  rule_row public.recurring_expenses%rowtype;
  generated_id bigint;
  generated_count integer := 0;
  scheduled_date date;
begin
  for rule_row in
    select * from public.recurring_expenses
    where active and next_run_date <= p_through_date and (end_date is null or next_run_date <= end_date)
    order by next_run_date, id for update skip locked
  loop
    scheduled_date := rule_row.next_run_date;
    while scheduled_date <= p_through_date and (rule_row.end_date is null or scheduled_date <= rule_row.end_date) loop
      if not exists (select 1 from public.recurring_expense_occurrences where rule_id = rule_row.id and scheduled_for = scheduled_date) then
        insert into public.expenses(transaction_date, amount, title, category, payer, memo)
        values (scheduled_date, rule_row.amount, rule_row.title, rule_row.category, rule_row.payer,
          concat_ws(E'\n', nullif(rule_row.memo, ''), '定期登録 #' || rule_row.id))
        returning id into generated_id;
        insert into public.recurring_expense_occurrences(rule_id, scheduled_for, expense_id)
        values (rule_row.id, scheduled_date, generated_id);
        generated_count := generated_count + 1;
      end if;
      scheduled_date := public.next_recurring_date(scheduled_date, rule_row.frequency, rule_row.interval_count, rule_row.day_of_month);
    end loop;
    update public.recurring_expenses set
      next_run_date = scheduled_date,
      active = case when end_date is not null and scheduled_date > end_date then false else active end,
      last_generated_at = case when scheduled_date <> rule_row.next_run_date then now() else last_generated_at end,
      updated_at = now()
    where id = rule_row.id;
  end loop;
  return generated_count;
end
$$;

create or replace function public.set_recurring_expense_active(p_id bigint, p_active boolean)
returns setof public.recurring_expenses
language plpgsql security definer set search_path = public as $$
declare
  rule_row public.recurring_expenses%rowtype;
  candidate date;
  today_jst date := (now() at time zone 'Asia/Tokyo')::date;
begin
  select * into strict rule_row from public.recurring_expenses where id = p_id for update;
  candidate := rule_row.next_run_date;
  if p_active then
    while candidate <= today_jst loop
      candidate := public.next_recurring_date(candidate, rule_row.frequency, rule_row.interval_count, rule_row.day_of_month);
    end loop;
  end if;
  update public.recurring_expenses set
    active = p_active and (end_date is null or candidate <= end_date),
    next_run_date = candidate,
    updated_at = now()
  where id = p_id
  returning * into rule_row;
  return next rule_row;
end
$$;

create or replace function public.update_recurring_expense_rule(
  p_id bigint,
  p_frequency text,
  p_interval_count integer,
  p_end_date date,
  p_amount bigint,
  p_title text,
  p_category text,
  p_payer text,
  p_memo text
) returns setof public.recurring_expenses
language plpgsql security definer set search_path = public as $$
declare
  rule_row public.recurring_expenses%rowtype;
  candidate date;
  today_jst date := (now() at time zone 'Asia/Tokyo')::date;
begin
  if p_frequency not in ('daily', 'weekly', 'monthly') or p_interval_count not between 1 and 365 then raise exception 'invalid recurring schedule'; end if;
  if p_amount = 0 or length(btrim(p_title)) not between 1 and 200 then raise exception 'invalid recurring values'; end if;
  select * into strict rule_row from public.recurring_expenses where id = p_id for update;
  if p_end_date is not null and p_end_date < rule_row.start_date then raise exception 'end date precedes start date'; end if;
  candidate := rule_row.start_date;
  while candidate <= today_jst loop
    candidate := public.next_recurring_date(candidate, p_frequency, p_interval_count, rule_row.day_of_month);
  end loop;
  update public.recurring_expenses set
    frequency = p_frequency,
    interval_count = p_interval_count,
    end_date = p_end_date,
    next_run_date = candidate,
    active = active and (p_end_date is null or candidate <= p_end_date),
    amount = p_amount,
    title = btrim(p_title),
    category = btrim(p_category),
    payer = nullif(btrim(p_payer), ''),
    memo = nullif(btrim(p_memo), ''),
    updated_at = now()
  where id = p_id
  returning * into rule_row;
  return next rule_row;
end
$$;

revoke all on function public.create_recurring_expense_rule(bigint, date, text, integer, date, bigint, text, text, text, text) from public, anon, authenticated;
revoke all on function public.materialize_recurring_expenses(date) from public, anon, authenticated;
revoke all on function public.set_recurring_expense_active(bigint, boolean) from public, anon, authenticated;
revoke all on function public.update_recurring_expense_rule(bigint, text, integer, date, bigint, text, text, text, text) from public, anon, authenticated;
grant execute on function public.create_recurring_expense_rule(bigint, date, text, integer, date, bigint, text, text, text, text) to service_role;
grant execute on function public.materialize_recurring_expenses(date) to service_role;
grant execute on function public.set_recurring_expense_active(bigint, boolean) to service_role;
grant execute on function public.update_recurring_expense_rule(bigint, text, integer, date, bigint, text, text, text, text) to service_role;

create extension if not exists pg_cron with schema extensions;
do $$ begin
  if not exists (select 1 from cron.job where jobname = 'materialize-recurring-expenses-jst') then
    perform cron.schedule(
      'materialize-recurring-expenses-jst',
      '10 15 * * *',
      'select public.materialize_recurring_expenses();'
    );
  end if;
end $$;
