-- Mastery was stored only as the current value, so its progression over time could not be charted.
-- Every change is appended here from now on; existing rows get one baseline event at migration time.
create table if not exists public.knowledge_mastery_history (
  id bigint generated by default as identity primary key,
  knowledge_id uuid not null references public.knowledge(id) on delete cascade,
  from_mastery text check (from_mastery is null or from_mastery in ('未学習', '学習中', '習得中', '定着')),
  to_mastery text not null check (to_mastery in ('未学習', '学習中', '習得中', '定着')),
  is_baseline boolean not null default false,
  changed_at timestamptz not null default now()
);

create index if not exists knowledge_mastery_history_changed_at_idx
  on public.knowledge_mastery_history (changed_at asc, id asc);
create index if not exists knowledge_mastery_history_knowledge_idx
  on public.knowledge_mastery_history (knowledge_id, changed_at desc);

alter table public.knowledge_mastery_history enable row level security;
revoke all on table public.knowledge_mastery_history from public, anon, authenticated;
grant select on table public.knowledge_mastery_history to service_role;

-- SECURITY DEFINER so that any role allowed to update knowledge (record_answer, the chat skill,
-- the dashboard API) can append history without needing direct rights on this table.
create or replace function public.log_knowledge_mastery_change()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.knowledge_mastery_history (knowledge_id, from_mastery, to_mastery)
    values (new.id, null, new.mastery);
  elsif new.mastery is distinct from old.mastery then
    insert into public.knowledge_mastery_history (knowledge_id, from_mastery, to_mastery)
    values (new.id, old.mastery, new.mastery);
  end if;
  return null;
end;
$$;

revoke all on function public.log_knowledge_mastery_change() from public, anon, authenticated;

drop trigger if exists knowledge_mastery_history_trigger on public.knowledge;
create trigger knowledge_mastery_history_trigger
  after insert or update of mastery on public.knowledge
  for each row execute function public.log_knowledge_mastery_change();

insert into public.knowledge_mastery_history (knowledge_id, from_mastery, to_mastery, is_baseline, changed_at)
select k.id, null, k.mastery, true, now()
from public.knowledge k
where not exists (
  select 1 from public.knowledge_mastery_history h where h.knowledge_id = k.id
);
