-- Review queue: questions are generated in scheduled batches and answers are
-- graded in scheduled batches, instead of calling the AI on every request.
--
-- * review_queue holds one question per row through its whole life:
--   ready (generated, waiting to be served) -> answered (waiting for grading)
--   -> grading -> graded, or error after repeated grading failures, or
--   discarded when the knowledge changed or was answered through another path.
-- * At most one active (ready/answered/grading/error) question exists per card.
-- * quiz_log keeps the official record and now also stores the question, the
--   answer, the model answer and the feedback so the learning log can show them.
-- * Scheduling uses the time of the answer, not the time of grading.
begin;

create table if not exists public.review_queue (
  id bigint generated by default as identity primary key,
  knowledge_id uuid not null references public.knowledge(id) on delete cascade,
  content_version bigint not null,
  format text not null check (format in ('一問一答', '四択', '記述説明', '産出')),
  question text not null check (char_length(btrim(question)) between 1 and 2000),
  choices jsonb,
  correct_choice text,
  -- Feedback prepared at generation time so a multiple-choice answer can be
  -- recorded instantly without another AI call.
  prepared_explanation text check (prepared_explanation is null or char_length(prepared_explanation) <= 2000),
  status text not null default 'ready'
    check (status in ('ready', 'answered', 'grading', 'graded', 'error', 'discarded')),
  generated_at timestamptz not null default now(),
  answer_text text check (answer_text is null or char_length(answer_text) <= 2000),
  answered_at timestamptz,
  grade_attempts smallint not null default 0 check (grade_attempts >= 0),
  grading_started_at timestamptz,
  last_error text,
  graded_at timestamptz,
  discarded_reason text,
  constraint review_queue_choice_shape check (
    (format = '四択' and jsonb_typeof(choices) = 'array' and jsonb_array_length(choices) = 4
      and correct_choice is not null and choices ? correct_choice)
    or (format <> '四択' and choices is null and correct_choice is null)
  ),
  constraint review_queue_answer_shape check (
    status in ('ready', 'discarded') or (answered_at is not null and answer_text is not null)
  )
);

create unique index if not exists review_queue_one_active_per_knowledge
  on public.review_queue (knowledge_id)
  where status in ('ready', 'answered', 'grading', 'error');
create index if not exists review_queue_status_idx
  on public.review_queue (status, generated_at);

alter table public.review_queue enable row level security;
revoke all on table public.review_queue from public, anon, authenticated;
grant select, insert, update, delete on table public.review_queue to service_role;

comment on table public.review_queue is
  'Pre-generated review questions and pending answers. One active row per knowledge card.';

alter table public.quiz_log
  add column if not exists question text,
  add column if not exists user_answer text,
  add column if not exists correct_answer text,
  add column if not exists explanation text,
  add column if not exists answered_at timestamptz,
  add column if not exists confirmed_at timestamptz,
  add column if not exists review_queue_id bigint;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.quiz_log'::regclass and conname = 'quiz_log_review_queue_fk'
  ) then
    alter table public.quiz_log
      add constraint quiz_log_review_queue_fk
      foreign key (review_queue_id) references public.review_queue(id) on delete set null;
  end if;
end
$$;

create unique index if not exists quiz_log_review_queue_unique
  on public.quiz_log (review_queue_id) where review_queue_id is not null;
create index if not exists quiz_log_unconfirmed_idx
  on public.quiz_log (created_at desc) where review_queue_id is not null and confirmed_at is null;

create table if not exists public.review_batch_runs (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('generate', 'grade')),
  trigger text not null check (trigger in ('schedule', 'manual', 'after_grade')),
  status text not null default 'running' check (status in ('running', 'succeeded', 'skipped', 'failed')),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  processed integer not null default 0,
  succeeded integer not null default 0,
  failed integer not null default 0,
  note text
);
create index if not exists review_batch_runs_kind_idx on public.review_batch_runs (kind, started_at desc);

alter table public.review_batch_runs enable row level security;
revoke all on table public.review_batch_runs from public, anon, authenticated;
grant select, insert, update, delete on table public.review_batch_runs to service_role;

-- Limits shared by the batches, the API and the status display.
create or replace function public.review_queue_limit()
returns integer language sql immutable set search_path to 'public', 'pg_temp'
as $$ select 200 $$;

create or replace function public.review_generation_batch_size()
returns integer language sql immutable set search_path to 'public', 'pg_temp'
as $$ select 30 $$;

create or replace function public.review_grading_max_attempts()
returns integer language sql immutable set search_path to 'public', 'pg_temp'
as $$ select 3 $$;

-- Only one run of each kind at a time. A run older than 15 minutes is treated
-- as abandoned so a crashed batch never blocks later ones.
create or replace function public.begin_review_batch(p_kind text, p_trigger text)
returns bigint
language plpgsql
set search_path to 'public', 'pg_temp'
as $$
declare
  v_id bigint;
begin
  if p_kind not in ('generate', 'grade') or p_trigger not in ('schedule', 'manual', 'after_grade') then
    raise exception 'invalid review batch' using errcode = '22023';
  end if;
  perform pg_advisory_xact_lock(hashtext('review_batch_' || p_kind));

  update public.review_batch_runs
  set status = 'failed', finished_at = now(), note = coalesce(note, '15分以内に終わらなかったため打ち切り扱いにしました。')
  where kind = p_kind and status = 'running' and started_at < now() - interval '15 minutes';

  if exists (select 1 from public.review_batch_runs where kind = p_kind and status = 'running') then
    return null;
  end if;

  delete from public.review_batch_runs where started_at < now() - interval '30 days';

  insert into public.review_batch_runs (kind, trigger) values (p_kind, p_trigger)
  returning id into v_id;
  return v_id;
end
$$;

create or replace function public.finish_review_batch(
  p_run_id bigint,
  p_status text,
  p_processed integer default 0,
  p_succeeded integer default 0,
  p_failed integer default 0,
  p_note text default null
)
returns void
language sql
set search_path to 'public', 'pg_temp'
as $$
  update public.review_batch_runs
  set status = p_status,
      finished_at = now(),
      processed = greatest(0, coalesce(p_processed, 0)),
      succeeded = greatest(0, coalesce(p_succeeded, 0)),
      failed = greatest(0, coalesce(p_failed, 0)),
      note = left(p_note, 1000)
  where id = p_run_id and status = 'running'
    and p_status in ('succeeded', 'skipped', 'failed');
$$;

-- Discard ready questions that no longer match their card: the card was
-- archived, edited, or answered through another path (e.g. the chat skill).
create or replace function public.discard_stale_review_questions()
returns integer
language sql
set search_path to 'public', 'pg_temp'
as $$
  with stale as (
    update public.review_queue q
    set status = 'discarded',
        discarded_reason = case
          when k.archived then 'archived'
          when k.content_version <> q.content_version then 'edited'
          else 'answered_elsewhere'
        end
    from public.knowledge k
    where q.knowledge_id = k.id
      and q.status = 'ready'
      and (
        k.archived
        or k.content_version <> q.content_version
        or (k.last_reviewed_at is not null and k.last_reviewed_at > q.generated_at)
      )
    returning 1
  )
  select count(*)::integer from stale;
$$;

-- Cards that should get a question in the next generation batch: due now or
-- within 30 minutes, with no active question. Never-asked cards stay within the
-- daily new-card allowance, counting cards first answered today and new cards
-- already waiting in the queue. Ordered like the daily review queue.
create or replace function public.pick_review_generation_candidates(
  p_limit integer default 30,
  p_relearning_only boolean default false
)
returns table(
  id uuid,
  title text,
  explanation text,
  category text,
  tags text[],
  mastery text,
  times_asked integer,
  pool text,
  stability_hours numeric,
  relearning_stage text,
  content_version bigint
)
language sql
stable
set search_path to 'public', 'pg_temp'
as $$
  with active as (
    select q.knowledge_id
    from public.review_queue q
    where q.status in ('ready', 'answered', 'grading', 'error')
  ),
  new_in_queue as (
    select count(*)::integer as n
    from public.review_queue q
    join public.knowledge k on k.id = q.knowledge_id
    where q.status in ('ready', 'answered', 'grading', 'error') and k.times_asked = 0
  ),
  allowance as (
    select greatest(0, public.review_new_cards_remaining_today() - (select n from new_in_queue)) as new_slots
  ),
  eligible as (
    select
      k.*,
      case
        when k.relearning_stage is not null then 'R'::text
        when k.times_asked = 0 then 'B'::text
        else 'A'::text
      end as pool
    from public.knowledge k
    where k.archived = false
      and k.next_review_at <= now() + interval '30 minutes'
      and not exists (select 1 from active a where a.knowledge_id = k.id)
  ),
  new_ranked as (
    select e.id, row_number() over (
      order by
        case e.priority when '最高' then 0 when '高' then 1 when '中' then 2 when '低' then 3 else 4 end,
        e.created_at,
        e.id
    ) as rank_no
    from eligible e
    where e.pool = 'B'
  ),
  selectable as (
    select e.*
    from eligible e
    where (not p_relearning_only or e.pool = 'R')
      and (
        e.pool <> 'B'
        or e.id in (select n.id from new_ranked n cross join allowance a where n.rank_no <= a.new_slots)
      )
  )
  select
    s.id, s.title, s.explanation, s.category, s.tags, s.mastery, s.times_asked, s.pool,
    s.stability_hours, s.relearning_stage, s.content_version
  from selectable s
  order by
    case s.pool when 'R' then 0 when 'A' then 1 else 2 end,
    case when s.pool = 'R' then s.relearning_quality else 4 end asc nulls last,
    case s.priority when '最高' then 0 when '高' then 1 when '中' then 2 when '低' then 3 else 4 end,
    s.next_review_at,
    s.id
  limit greatest(0, least(coalesce(p_limit, 30), public.review_generation_batch_size()));
$$;

-- Store generated questions. Skips a card whose content changed since it was
-- picked or that already has an active question, and never fills past the
-- queue limit. Returns how many questions were added.
create or replace function public.enqueue_review_questions(p_items jsonb)
returns integer
language plpgsql
set search_path to 'public', 'pg_temp'
as $$
declare
  item record;
  v_ready integer;
  v_added integer := 0;
  v_rows integer;
begin
  if jsonb_typeof(p_items) is distinct from 'array' or jsonb_array_length(p_items) > 30 then
    raise exception 'p_items must be an array of at most 30 items' using errcode = '22023';
  end if;
  perform pg_advisory_xact_lock(hashtext('review_queue_enqueue'));
  select count(*) into v_ready from public.review_queue where status = 'ready';

  for item in
    select * from jsonb_to_recordset(p_items) as parsed(
      knowledge_id uuid,
      content_version bigint,
      format text,
      question text,
      choices jsonb,
      correct_choice text,
      prepared_explanation text
    )
  loop
    exit when v_ready >= public.review_queue_limit();
    insert into public.review_queue (
      knowledge_id, content_version, format, question, choices, correct_choice, prepared_explanation
    )
    select item.knowledge_id, item.content_version, item.format, btrim(item.question),
      case when item.format = '四択' then item.choices end,
      case when item.format = '四択' then item.correct_choice end,
      nullif(btrim(coalesce(item.prepared_explanation, '')), '')
    from public.knowledge k
    where k.id = item.knowledge_id and k.archived = false and k.content_version = item.content_version
    on conflict (knowledge_id) where status in ('ready', 'answered', 'grading', 'error') do nothing;
    get diagnostics v_rows = row_count;
    v_added := v_added + v_rows;
    v_ready := v_ready + v_rows;
  end loop;
  return v_added;
end
$$;

-- Ready questions whose card is due now, ordered like the daily review queue
-- (relearning first, at least five normal cards per batch when available).
-- Stale questions are discarded first. Served questions stay ready until answered.
create or replace function public.serve_review_queue(
  p_limit integer default 15,
  p_categories text[] default null
)
returns table(
  id bigint,
  knowledge_id uuid,
  format text,
  question text,
  choices jsonb,
  category text,
  pool text
)
language plpgsql
set search_path to 'public', 'pg_temp'
as $$
begin
  perform public.discard_stale_review_questions();
  return query
  with params as (
    select greatest(1, least(coalesce(p_limit, 15), 30))::integer as batch_limit
  ),
  eligible as (
    select
      q.id as item_id, q.knowledge_id as card_id, q.format as item_format, q.question as item_question,
      q.choices as item_choices, k.category as card_category, k.relearning_quality, k.priority,
      k.next_review_at, k.accuracy, k.times_asked,
      case
        when k.relearning_stage is not null then 'R'::text
        when k.times_asked = 0 then 'B'::text
        else 'A'::text
      end as card_pool
    from public.review_queue q
    join public.knowledge k on k.id = q.knowledge_id
    where q.status = 'ready'
      and k.archived = false
      and k.next_review_at <= now()
      and (p_categories is null or k.category = any(p_categories))
  ),
  counts as (
    select count(*) filter (where card_pool <> 'R')::integer as normal_count from eligible
  ),
  retry_ranked as (
    select e.*, row_number() over (
      order by
        e.relearning_quality asc nulls last,
        case e.priority when '最高' then 0 when '高' then 1 when '中' then 2 when '低' then 3 else 4 end,
        e.accuracy asc nulls first,
        e.next_review_at,
        e.item_id
    ) as rank_no
    from eligible e where e.card_pool = 'R'
  ),
  retry_selected as (
    select r.* from retry_ranked r cross join counts c cross join params p
    where r.rank_no <= p.batch_limit - least(5, c.normal_count, p.batch_limit)
  ),
  normal_ranked as (
    select e.*, row_number() over (
      order by
        case e.card_pool when 'A' then 0 else 1 end,
        case e.priority when '最高' then 0 when '高' then 1 when '中' then 2 when '低' then 3 else 4 end,
        e.next_review_at,
        e.accuracy asc nulls first,
        e.times_asked,
        e.item_id
    ) as rank_no
    from eligible e where e.card_pool <> 'R'
  ),
  normal_selected as (
    select n.* from normal_ranked n cross join params p
    where n.rank_no <= p.batch_limit - (select count(*) from retry_selected)
  ),
  selected as (
    select * from retry_selected
    union all
    select * from normal_selected
  )
  select s.item_id, s.card_id, s.item_format, s.item_question, s.item_choices, s.card_category, s.card_pool
  from selected s
  order by
    case s.card_pool when 'R' then 0 when 'A' then 1 else 2 end,
    case when s.card_pool = 'R' then s.relearning_quality else 4 end asc nulls last,
    case s.priority when '最高' then 0 when '高' then 1 when '中' then 2 when '低' then 3 else 4 end,
    s.next_review_at,
    s.item_id;
end
$$;

-- Accept an answer for a ready question. Re-sending the same answer is a no-op,
-- so a retried request cannot create a second answer. The correct choice and
-- prepared feedback are returned only to the server for instant recording.
create or replace function public.submit_review_answer(p_item_id bigint, p_answer text)
returns table(
  id bigint,
  knowledge_id uuid,
  format text,
  question text,
  choices jsonb,
  correct_choice text,
  prepared_explanation text,
  answer_text text,
  answered_at timestamptz,
  status text,
  accepted boolean
)
language plpgsql
set search_path to 'public', 'pg_temp'
as $$
declare
  item public.review_queue;
  k public.knowledge;
  v_answer text := btrim(coalesce(p_answer, ''));
  v_accepted boolean := false;
begin
  if char_length(v_answer) > 2000 then
    raise exception 'answer is too long' using errcode = '22023';
  end if;

  select * into item from public.review_queue q where q.id = p_item_id for update;
  if not found then
    raise exception 'review question % was not found', p_item_id using errcode = 'P0002';
  end if;

  if item.status = 'ready' then
    select * into k from public.knowledge kk where kk.id = item.knowledge_id;
    if k.archived or k.content_version <> item.content_version
      or (k.last_reviewed_at is not null and k.last_reviewed_at > item.generated_at) then
      update public.review_queue q set status = 'discarded', discarded_reason = 'stale_on_answer'
      where q.id = item.id;
      raise exception 'review question % is no longer valid', p_item_id using errcode = 'P0001';
    end if;
    if item.format = '四択' and v_answer <> '' and not (item.choices ? v_answer) then
      raise exception 'answer is not one of the choices' using errcode = '22023';
    end if;
    update public.review_queue q
    set status = 'answered', answer_text = v_answer, answered_at = now()
    where q.id = item.id
    returning * into item;
    v_accepted := true;
  elsif item.status in ('answered', 'grading', 'graded', 'error') then
    if item.answer_text is distinct from v_answer then
      raise exception 'review question % was already answered', p_item_id using errcode = 'P0001';
    end if;
  else
    raise exception 'review question % is no longer valid', p_item_id using errcode = 'P0001';
  end if;

  return query select item.id, item.knowledge_id, item.format, item.question, item.choices,
    item.correct_choice, item.prepared_explanation, item.answer_text, item.answered_at, item.status, v_accepted;
end
$$;

-- Claim answers for one grading batch. Answers stuck in grading for more than
-- 10 minutes are returned to the waiting state first.
create or replace function public.claim_review_answers(p_limit integer default 30)
returns table(
  id bigint,
  knowledge_id uuid,
  format text,
  question text,
  choices jsonb,
  correct_choice text,
  prepared_explanation text,
  answer_text text,
  answered_at timestamptz,
  grade_attempts smallint
)
language plpgsql
set search_path to 'public', 'pg_temp'
as $$
begin
  update public.review_queue q
  set status = 'answered', grading_started_at = null
  where q.status = 'grading' and q.grading_started_at < now() - interval '10 minutes';

  return query
  with claimed as (
    select q.id from public.review_queue q
    where q.status = 'answered'
    order by q.answered_at, q.id
    limit greatest(1, least(coalesce(p_limit, 30), 30))
    for update skip locked
  )
  update public.review_queue q
  set status = 'grading', grading_started_at = now(), grade_attempts = q.grade_attempts + 1
  from claimed c
  where q.id = c.id
  returning q.id, q.knowledge_id, q.format, q.question, q.choices, q.correct_choice,
    q.prepared_explanation, q.answer_text, q.answered_at, q.grade_attempts;
end
$$;

-- Give a failed answer back to the next batch, or mark it as an error after the
-- maximum number of attempts so it can be retried by hand from the learning log.
create or replace function public.release_review_answer(p_item_id bigint, p_error text)
returns text
language sql
set search_path to 'public', 'pg_temp'
as $$
  update public.review_queue q
  set status = case when q.grade_attempts >= public.review_grading_max_attempts() then 'error' else 'answered' end,
      grading_started_at = null,
      last_error = left(p_error, 1000)
  where q.id = p_item_id and q.status in ('grading', 'answered')
  returning q.status;
$$;

-- Manual retry of an answer that reached the error state.
create or replace function public.retry_review_answer(p_item_id bigint)
returns text
language sql
set search_path to 'public', 'pg_temp'
as $$
  update public.review_queue q
  set status = 'answered', grade_attempts = 0, grading_started_at = null, last_error = null
  where q.id = p_item_id and q.status = 'error'
  returning q.status;
$$;

-- record_answer gains p_answered_at so an answer graded later is scheduled
-- from when it was given. The 5-argument calls keep working through the default.
drop function if exists public.record_answer(uuid, smallint, text, text, text);
create function public.record_answer(
  p_knowledge_id uuid,
  p_quality smallint,
  p_verdict text,
  p_note text default null,
  p_format text default '一問一答',
  p_answered_at timestamptz default null
)
returns public.knowledge
language plpgsql
set search_path to 'public', 'pg_temp'
as $$
declare
  k public.knowledge;
  -- 採点を後から行う回答は、回答した時刻を予定の起点にする。未来の時刻は受け付けない。
  v_now timestamptz := least(coalesce(p_answered_at, clock_timestamp()), clock_timestamp());
  v_today date := (v_now at time zone 'Asia/Tokyo')::date;
  v_mastery text;
  v_streak smallint;
  v_stability numeric;
  v_due_hours numeric;
  v_next_at timestamptz;
  v_stage text;
  v_relearning_quality smallint;
  v_relearning_penalized boolean;
  v_in_relearning boolean;
  v_was_early boolean;
  v_schedule_updated boolean := true;
  v_ef numeric(4, 2);
  v_reps integer;
begin
  if p_quality is null or p_quality < 0 or p_quality > 5
    or p_verdict not in ('正解', '部分正解', '不正解')
    or p_format not in ('一問一答', '四択', '記述説明', '産出') then
    raise exception 'invalid answer values' using errcode = '22023';
  end if;

  select * into strict k
  from public.knowledge
  where id = p_knowledge_id and archived = false
  for update;

  v_mastery := case when k.mastery = '未学習' then '学習中' else k.mastery end;
  v_streak := k.mastery_streak;
  v_stability := k.stability_hours;
  v_stage := k.relearning_stage;
  v_relearning_quality := k.relearning_quality;
  v_relearning_penalized := k.relearning_penalized;
  v_in_relearning := k.relearning_stage is not null;
  v_was_early := k.next_review_at > v_now;
  v_ef := k.ef;
  v_reps := k.reps;

  -- A successful early/custom review is evidence, but must not move the
  -- scheduled date, grow stability or promote mastery.
  if v_was_early and p_quality >= 4 then
    v_schedule_updated := false;
  else
    v_ef := greatest(
      1.30,
      round(k.ef + (0.1 - (5 - p_quality) * (0.08 + (5 - p_quality) * 0.02)), 2)
    );
    v_reps := case when p_quality < 3 then 0 else k.reps + 1 end;

    if p_quality <= 3 then
      -- Apply stability loss and mastery demotion only once per lapse episode.
      if not v_relearning_penalized then
        v_stability := least(8760, greatest(0, v_stability * case p_quality
          when 0 then 0.40
          when 1 then 0.55
          when 2 then 0.70
          else 0.85
        end));
        v_streak := 0;
        if p_quality <= 2 then
          v_mastery := case v_mastery
            when '定着' then '習得中'
            when '習得中' then '学習中'
            else '学習中'
          end;
        end if;
        v_relearning_penalized := true;
      end if;

      -- Relearning steps are short and fixed; priority does not stretch them.
      v_stage := case when p_quality <= 2 then 'recognition' else 'recall' end;
      v_relearning_quality := p_quality;
      v_due_hours := case p_quality
        when 0 then 10.0 / 60
        when 1 then 30.0 / 60
        when 2 then 6
        else 12
      end;
    elsif p_format = '四択' then
      -- Recognition alone never grows stability or mastery. Confirm it later
      -- with a free-response recall.
      v_stage := 'recall';
      v_relearning_quality := null;
      v_due_hours := 24;
    elsif v_in_relearning then
      -- The first successful free recall restores the retained interval without
      -- applying another growth multiplier.
      v_stability := least(8760, greatest(
        v_stability,
        case p_quality when 4 then 24 else 72 end
      ));
      v_due_hours := least(8760, v_stability * public.review_priority_factor(k.priority));
      v_stage := null;
      v_relearning_quality := null;
      v_relearning_penalized := false;
    else
      -- Strong, due, free-response recall grows long-term stability.
      v_stability := least(8760, case p_quality
        when 4 then greatest(48, case when v_stability <= 0 then 48 else v_stability * 2.00 end)
        else greatest(96, case when v_stability <= 0 then 96 else v_stability * 2.80 end)
      end);
      v_due_hours := least(8760, v_stability * public.review_priority_factor(k.priority));
      v_streak := least(3, v_streak + 1);

      if v_mastery = '学習中' and v_streak >= 3 and v_stability >= 72 then
        v_mastery := '習得中';
        v_streak := 0;
      elsif v_mastery = '習得中' and v_streak >= 3 and v_stability >= 720 then
        v_mastery := '定着';
        v_streak := 0;
      end if;
    end if;

    v_next_at := v_now + make_interval(secs => (v_due_hours * 3600)::double precision);
  end if;

  update public.knowledge
  set
    ef = v_ef,
    reps = v_reps,
    base_interval_days = greatest(0, ceil(v_stability / 24)::integer),
    interval_days = case when v_schedule_updated
      then greatest(1, ceil(v_due_hours / 24)::integer)
      else interval_days
    end,
    mastery = v_mastery,
    mastery_streak = v_streak,
    times_asked = times_asked + 1,
    times_correct = times_correct + case when p_quality >= 3 then 1 else 0 end,
    last_asked_on = v_today,
    last_reviewed_at = v_now,
    scheduled_from_at = case when v_schedule_updated then v_now else scheduled_from_at end,
    next_review_at = case when v_schedule_updated then v_next_at else next_review_at end,
    next_review_on = case when v_schedule_updated
      then (v_next_at at time zone 'Asia/Tokyo')::date
      else next_review_on
    end,
    stability_hours = v_stability,
    relearning_stage = v_stage,
    relearning_quality = v_relearning_quality,
    relearning_penalized = v_relearning_penalized
  where id = p_knowledge_id
  returning * into k;

  insert into public.quiz_log(
    knowledge_id, asked_on, quality, verdict, format, note, was_early, schedule_updated, created_at
  ) values (
    p_knowledge_id, v_today, p_quality, p_verdict, p_format, p_note,
    v_was_early, v_schedule_updated, v_now
  );

  return k;
end
$$;


-- Record a graded queue answer exactly once, from the time it was answered, and
-- keep the question, answer, model answer and feedback with the official record.
create or replace function public.record_review_grade(
  p_item_id bigint,
  p_quality smallint,
  p_verdict text,
  p_note text,
  p_correct_answer text,
  p_explanation text
)
returns table(
  item_id bigint,
  quiz_log_id bigint,
  recorded boolean,
  status text,
  next_review_at timestamptz
)
language plpgsql
set search_path to 'public', 'pg_temp'
as $$
declare
  item public.review_queue;
  k public.knowledge;
  v_log_id bigint;
  v_next timestamptz;
begin
  select * into item from public.review_queue q where q.id = p_item_id for update;
  if not found then
    raise exception 'review question % was not found', p_item_id using errcode = 'P0002';
  end if;

  if item.status = 'graded' then
    select l.id into v_log_id from public.quiz_log l where l.review_queue_id = item.id;
    select kk.next_review_at into v_next from public.knowledge kk where kk.id = item.knowledge_id;
    return query select item.id, v_log_id, false, item.status, v_next;
    return;
  end if;
  if item.status not in ('answered', 'grading', 'error') then
    raise exception 'review question % cannot be graded in status %', p_item_id, item.status
      using errcode = 'P0001';
  end if;

  select * into k from public.knowledge kk where kk.id = item.knowledge_id for update;
  if not found or k.archived then
    update public.review_queue q set status = 'discarded', discarded_reason = 'archived'
    where q.id = item.id;
    return query select item.id, null::bigint, false, 'discarded'::text, null::timestamptz;
    return;
  end if;
  -- The card was answered through another path after this answer. Recording an
  -- older answer on top would apply the schedule out of order.
  if k.last_reviewed_at is not null and k.last_reviewed_at > item.answered_at then
    update public.review_queue q set status = 'discarded', discarded_reason = 'answered_elsewhere'
    where q.id = item.id;
    return query select item.id, null::bigint, false, 'discarded'::text, k.next_review_at;
    return;
  end if;

  k := public.record_answer(
    item.knowledge_id, p_quality, p_verdict, p_note, item.format, item.answered_at
  );

  select l.id into strict v_log_id
  from public.quiz_log l
  where l.knowledge_id = item.knowledge_id
  order by l.id desc
  limit 1;

  update public.quiz_log l
  set question = item.question,
      user_answer = item.answer_text,
      correct_answer = left(p_correct_answer, 4000),
      explanation = left(p_explanation, 8000),
      answered_at = item.answered_at,
      review_queue_id = item.id
  where l.id = v_log_id;

  update public.review_queue q
  set status = 'graded', graded_at = now(), grading_started_at = null, last_error = null
  where q.id = item.id;

  return query select item.id, v_log_id, true, 'graded'::text, k.next_review_at;
end
$$;

-- Mark results as seen in the learning log.
create or replace function public.confirm_review_results(p_quiz_log_ids bigint[])
returns integer
language sql
set search_path to 'public', 'pg_temp'
as $$
  with confirmed as (
    update public.quiz_log l
    set confirmed_at = now()
    where l.id = any(p_quiz_log_ids) and l.review_queue_id is not null and l.confirmed_at is null
    returning 1
  )
  select count(*)::integer from confirmed;
$$;

create or replace function public.get_review_queue_status()
returns table(
  ready_total integer,
  ready_due integer,
  waiting_grading integer,
  grading_errors integer,
  unconfirmed_results integer,
  queue_limit integer,
  queue_full boolean,
  last_generate_at timestamptz,
  last_generate_status text,
  last_generate_added integer,
  last_generate_note text,
  last_grade_at timestamptz,
  last_grade_status text
)
language sql
stable
set search_path to 'public', 'pg_temp'
as $$
  with counts as (
    select
      count(*) filter (where q.status = 'ready')::integer as ready_total,
      count(*) filter (where q.status = 'ready' and k.next_review_at <= now() and not k.archived
        and k.content_version = q.content_version)::integer as ready_due,
      count(*) filter (where q.status in ('answered', 'grading'))::integer as waiting_grading,
      count(*) filter (where q.status = 'error')::integer as grading_errors
    from public.review_queue q
    join public.knowledge k on k.id = q.knowledge_id
    where q.status in ('ready', 'answered', 'grading', 'error')
  ),
  last_generate as (
    select r.* from public.review_batch_runs r where r.kind = 'generate'
    order by r.started_at desc limit 1
  ),
  last_grade as (
    select r.* from public.review_batch_runs r where r.kind = 'grade'
    order by r.started_at desc limit 1
  )
  select
    c.ready_total,
    c.ready_due,
    c.waiting_grading,
    c.grading_errors,
    (select count(*)::integer from public.quiz_log l where l.review_queue_id is not null and l.confirmed_at is null),
    public.review_queue_limit(),
    c.ready_total >= public.review_queue_limit(),
    (select g.started_at from last_generate g),
    (select g.status from last_generate g),
    (select g.succeeded from last_generate g),
    (select g.note from last_generate g),
    (select g.started_at from last_grade g),
    (select g.status from last_grade g)
  from counts c;
$$;

do $$
declare
  fn text;
begin
  foreach fn in array array[
    'public.review_queue_limit()',
    'public.review_generation_batch_size()',
    'public.review_grading_max_attempts()',
    'public.begin_review_batch(text, text)',
    'public.finish_review_batch(bigint, text, integer, integer, integer, text)',
    'public.discard_stale_review_questions()',
    'public.pick_review_generation_candidates(integer, boolean)',
    'public.enqueue_review_questions(jsonb)',
    'public.serve_review_queue(integer, text[])',
    'public.submit_review_answer(bigint, text)',
    'public.claim_review_answers(integer)',
    'public.release_review_answer(bigint, text)',
    'public.retry_review_answer(bigint)',
    'public.record_answer(uuid, smallint, text, text, text, timestamptz)',
    'public.record_review_grade(bigint, smallint, text, text, text, text)',
    'public.confirm_review_results(bigint[])',
    'public.get_review_queue_status()'
  ]
  loop
    execute format('revoke all on function %s from public, anon, authenticated', fn);
    execute format('grant execute on function %s to service_role', fn);
  end loop;
end
$$;

insert into public.dashboard_schema_versions (app_id, migration, updated_at)
values ('knowledge-dashboard', '20261002100000_review_queue', now())
on conflict (app_id) do update
set migration = excluded.migration,
    updated_at = excluded.updated_at;

notify pgrst, 'reload schema';

commit;
