-- 学んだナレッジが「自分にとってどう役立つか」を付箋のように残す。
-- 出題・採点・定着間隔の計算には一切使わない（pick_quiz や record_answer はこの表を読まない）。
create table if not exists public.knowledge_insights (
  id bigint generated by default as identity primary key,
  knowledge_id uuid not null references public.knowledge(id) on delete cascade,
  body text not null check (char_length(btrim(body)) between 1 and 1000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists knowledge_insights_knowledge_idx
  on public.knowledge_insights (knowledge_id, created_at desc);
create index if not exists knowledge_insights_created_at_idx
  on public.knowledge_insights (created_at desc, id desc);

alter table public.knowledge_insights enable row level security;
revoke all on table public.knowledge_insights from public, anon, authenticated;
grant select, insert, update, delete on table public.knowledge_insights to service_role;

comment on table public.knowledge_insights is
  'Personal takeaways written per knowledge entry. Never used for quiz selection or grading.';
