-- Curated questions connect individual takeaways without copying their text.
-- Reading or organizing groups never changes quiz_log or the review schedule.
begin;

create table if not exists public.insight_groups (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(btrim(title)) between 1 and 120),
  guiding_question text not null check (char_length(btrim(guiding_question)) between 1 and 300),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.insight_group_members (
  group_id bigint not null references public.insight_groups(id) on delete cascade,
  insight_id bigint not null references public.knowledge_insights(id) on delete cascade,
  primary key (group_id, insight_id)
);

create index if not exists insight_group_members_insight_idx
  on public.insight_group_members (insight_id, group_id);

-- A membership change also makes a stale group edit/delete fail its timestamp check.
create or replace function public.touch_insight_group_metadata()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if tg_op = 'UPDATE' then
    new.updated_at := greatest(clock_timestamp(), old.updated_at + interval '1 microsecond');
    return new;
  end if;

  if tg_op = 'DELETE' then
    update public.insight_groups
       set updated_at = greatest(clock_timestamp(), updated_at + interval '1 microsecond')
     where id = old.group_id;
    return old;
  end if;

  update public.insight_groups
     set updated_at = greatest(clock_timestamp(), updated_at + interval '1 microsecond')
   where id = new.group_id;
  return new;
end;
$$;

drop trigger if exists insight_groups_touch_metadata on public.insight_groups;
create trigger insight_groups_touch_metadata
before update of title, guiding_question on public.insight_groups
for each row execute function public.touch_insight_group_metadata();

drop trigger if exists insight_group_members_touch_group on public.insight_group_members;
create trigger insight_group_members_touch_group
after insert or delete on public.insight_group_members
for each row execute function public.touch_insight_group_metadata();

alter table public.insight_groups enable row level security;
alter table public.insight_group_members enable row level security;
revoke all on table public.insight_groups, public.insight_group_members from public, anon, authenticated;
grant select, insert, update, delete on table public.insight_groups, public.insight_group_members to service_role;
revoke all on function public.touch_insight_group_metadata() from public, anon, authenticated;

comment on table public.insight_groups is 'User-curated questions for connecting personal knowledge insights.';
comment on table public.insight_group_members is 'Many-to-many links to existing knowledge_insights; deleting a group never deletes an insight.';

insert into public.dashboard_schema_versions (app_id, migration, updated_at)
values ('knowledge-dashboard', '20260925100000_insight_groups', now())
on conflict (app_id) do update
set migration = excluded.migration,
    updated_at = excluded.updated_at;

notify pgrst, 'reload schema';

commit;
