-- Projects are outcome-oriented containers. Inbox and Want rows stay in their
-- original tables; project_items only records the relationship and treatment.

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 240),
  outcome text not null check (char_length(outcome) between 1 and 2000),
  theme text check (theme is null or char_length(theme) between 1 and 120),
  status text not null default 'active'
    check (status in ('active', 'waiting', 'on_hold', 'completed', 'dropped')),
  target_on date,
  review_on date,
  waiting_for text check (waiting_for is null or char_length(waiting_for) between 1 and 240),
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (status = 'waiting' and waiting_for is not null and review_on is not null) or
    (status = 'on_hold' and waiting_for is null and review_on is not null) or
    (status in ('active', 'completed', 'dropped') and waiting_for is null)
  ),
  check (
    (status = 'completed' and completed_at is not null) or
    (status <> 'completed' and completed_at is null)
  )
);

create table if not exists public.project_items (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete restrict,
  source_type text not null check (source_type in ('inbox', 'want')),
  source_id bigint not null check (source_id > 0),
  source_content text not null check (char_length(source_content) between 1 and 2000),
  treatment text not null default 'unprocessed'
    check (treatment in ('unprocessed', 'reference', 'action_source', 'rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (project_id, source_type, source_id)
);

create table if not exists public.project_actions (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete restrict,
  project_item_id bigint references public.project_items(id) on delete restrict,
  content text not null check (char_length(content) between 1 and 500),
  status text not null default 'queued'
    check (status in ('next', 'queued', 'waiting', 'done', 'cancelled')),
  due_on date,
  waiting_for text check (waiting_for is null or char_length(waiting_for) between 1 and 240),
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (status = 'waiting' and waiting_for is not null) or
    (status <> 'waiting' and waiting_for is null)
  ),
  check (
    (status = 'done' and completed_at is not null) or
    (status <> 'done' and completed_at is null)
  )
);

create unique index if not exists project_actions_one_next_idx
  on public.project_actions (project_id)
  where status = 'next';

create index if not exists projects_status_review_idx
  on public.projects (status, review_on, target_on);

create index if not exists project_items_project_treatment_idx
  on public.project_items (project_id, treatment, created_at desc);

create index if not exists project_actions_project_status_idx
  on public.project_actions (project_id, status, created_at desc);

alter table public.projects enable row level security;
alter table public.project_items enable row level security;
alter table public.project_actions enable row level security;

comment on table public.projects is 'Outcome-oriented projects with explicit completion criteria and review state.';
comment on table public.project_items is 'Links Inbox or Want source rows to a project without moving the source record.';
comment on column public.project_items.source_content is 'Immutable display snapshot; the source table remains canonical.';
comment on table public.project_actions is 'Project action queue. At most one row per project can have status next.';

create or replace function public.create_project_with_next_action(
  p_title text,
  p_outcome text,
  p_theme text,
  p_target_on date,
  p_next_action text
)
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_project_id bigint;
begin
  insert into public.projects (title, outcome, theme, target_on, status)
  values (
    btrim(p_title),
    btrim(p_outcome),
    nullif(btrim(p_theme), ''),
    p_target_on,
    'active'
  )
  returning id into v_project_id;

  insert into public.project_actions (project_id, content, status)
  values (v_project_id, btrim(p_next_action), 'next');

  return v_project_id;
end;
$$;

create or replace function public.resume_project_with_next_action(
  p_project_id bigint,
  p_project_updated_at timestamptz,
  p_next_action text
)
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_project public.projects%rowtype;
  v_action_id bigint;
begin
  select * into v_project
  from public.projects
  where id = p_project_id and updated_at = p_project_updated_at
  for update;

  if not found then
    raise exception 'PROJECT_CONFLICT';
  end if;
  if v_project.status not in ('waiting', 'on_hold') then
    raise exception 'PROJECT_NOT_RESUMABLE';
  end if;

  insert into public.project_actions (project_id, content, status)
  values (p_project_id, btrim(p_next_action), 'next')
  returning id into v_action_id;

  update public.projects
  set status = 'active', review_on = null, waiting_for = null, updated_at = now()
  where id = p_project_id;

  return v_action_id;
end;
$$;

create or replace function public.add_project_queued_action(
  p_project_id bigint,
  p_project_updated_at timestamptz,
  p_content text
)
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_project public.projects%rowtype;
  v_action_id bigint;
begin
  select * into v_project
  from public.projects
  where id = p_project_id and updated_at = p_project_updated_at
  for update;

  if not found then
    raise exception 'PROJECT_CONFLICT';
  end if;
  if v_project.status <> 'active' then
    raise exception 'PROJECT_NOT_ACTIVE';
  end if;

  insert into public.project_actions (project_id, content, status)
  values (p_project_id, btrim(p_content), 'queued')
  returning id into v_action_id;

  update public.projects
  set updated_at = now()
  where id = p_project_id;

  return v_action_id;
end;
$$;

create or replace function public.resolve_project_next_action(
  p_action_id bigint,
  p_action_updated_at timestamptz,
  p_resolution text,
  p_next_action_id bigint,
  p_next_action_content text,
  p_waiting_for text,
  p_review_on date
)
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_action public.project_actions%rowtype;
  v_project public.projects%rowtype;
  v_next_action_id bigint;
begin
  select * into v_action
  from public.project_actions
  where id = p_action_id and updated_at = p_action_updated_at and status = 'next'
  for update;

  if not found then
    raise exception 'ACTION_CONFLICT';
  end if;

  select * into v_project
  from public.projects
  where id = v_action.project_id
  for update;

  if v_project.status <> 'active' then
    raise exception 'PROJECT_NOT_ACTIVE';
  end if;

  update public.project_actions
  set status = 'done', completed_at = now(), updated_at = now()
  where id = v_action.id;

  if p_resolution = 'continue' then
    if (p_next_action_id is null) = (nullif(btrim(p_next_action_content), '') is null) then
      raise exception 'NEXT_ACTION_REQUIRED';
    end if;

    if p_next_action_id is not null then
      update public.project_actions
      set status = 'next', updated_at = now()
      where id = p_next_action_id
        and project_id = v_project.id
        and status = 'queued'
      returning id into v_next_action_id;
      if v_next_action_id is null then
        raise exception 'QUEUED_ACTION_NOT_FOUND';
      end if;
    else
      insert into public.project_actions (project_id, content, status)
      values (v_project.id, btrim(p_next_action_content), 'next')
      returning id into v_next_action_id;
    end if;

    update public.projects
    set status = 'active', review_on = null, waiting_for = null, updated_at = now()
    where id = v_project.id;
  elsif p_resolution = 'complete' then
    update public.projects
    set status = 'completed', completed_at = now(), review_on = null,
        waiting_for = null, updated_at = now()
    where id = v_project.id;
  elsif p_resolution = 'waiting' then
    if nullif(btrim(p_waiting_for), '') is null or p_review_on is null then
      raise exception 'WAITING_DETAILS_REQUIRED';
    end if;
    update public.projects
    set status = 'waiting', waiting_for = btrim(p_waiting_for), review_on = p_review_on,
        updated_at = now()
    where id = v_project.id;
  elsif p_resolution = 'on_hold' then
    if p_review_on is null then
      raise exception 'REVIEW_DATE_REQUIRED';
    end if;
    update public.projects
    set status = 'on_hold', waiting_for = null, review_on = p_review_on, updated_at = now()
    where id = v_project.id;
  else
    raise exception 'RESOLUTION_INVALID';
  end if;

  return v_project.id;
end;
$$;
