-- English speaking practice is intentionally independent from quiz_log and the review scheduler.
create table if not exists public.speaking_practice_log (
  id bigint generated by default as identity primary key,
  attempt_id uuid not null unique,
  session_id uuid not null,
  knowledge_id uuid not null references public.knowledge(id) on delete restrict,
  practice_type text not null check (practice_type in ('instant_composition', 'read_aloud')),
  rating text not null check (rating in ('smooth', 'almost', 'retry')),
  answer_text text check (answer_text is null or char_length(answer_text) <= 2000),
  repetitions smallint not null default 1 check (repetitions between 1 and 20),
  practiced_at timestamptz not null default now()
);

create index if not exists speaking_practice_log_practiced_at_idx
  on public.speaking_practice_log (practiced_at desc, id desc);
create index if not exists speaking_practice_log_knowledge_idx
  on public.speaking_practice_log (knowledge_id, practiced_at desc);
create index if not exists speaking_practice_log_session_idx
  on public.speaking_practice_log (session_id, practiced_at asc);

alter table public.speaking_practice_log enable row level security;
revoke all on table public.speaking_practice_log from public, anon, authenticated;
grant select on table public.speaking_practice_log to service_role;

create or replace function public.record_speaking_practice(
  p_attempt_id uuid,
  p_session_id uuid,
  p_knowledge_id uuid,
  p_practice_type text,
  p_rating text,
  p_answer_text text default null,
  p_repetitions integer default 1
)
returns setof public.speaking_practice_log
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  stored public.speaking_practice_log%rowtype;
begin
  if p_practice_type not in ('instant_composition', 'read_aloud') then
    raise exception 'invalid speaking practice type' using errcode = '22023';
  end if;
  if p_rating not in ('smooth', 'almost', 'retry') then
    raise exception 'invalid speaking practice rating' using errcode = '22023';
  end if;
  if p_repetitions < 1 or p_repetitions > 20 then
    raise exception 'invalid speaking practice repetitions' using errcode = '22023';
  end if;
  if p_answer_text is not null and char_length(p_answer_text) > 2000 then
    raise exception 'speaking practice answer is too long' using errcode = '22023';
  end if;
  if not exists (
    select 1 from public.knowledge k where k.id = p_knowledge_id and k.archived = false
  ) then
    raise exception 'active knowledge % was not found', p_knowledge_id using errcode = 'P0002';
  end if;

  insert into public.speaking_practice_log (
    attempt_id, session_id, knowledge_id, practice_type, rating, answer_text, repetitions
  ) values (
    p_attempt_id, p_session_id, p_knowledge_id, p_practice_type, p_rating,
    nullif(btrim(p_answer_text), ''), p_repetitions
  )
  on conflict (attempt_id) do nothing;

  select * into strict stored
  from public.speaking_practice_log spl
  where spl.attempt_id = p_attempt_id;

  if stored.session_id is distinct from p_session_id
    or stored.knowledge_id is distinct from p_knowledge_id
    or stored.practice_type is distinct from p_practice_type
    or stored.rating is distinct from p_rating
    or stored.answer_text is distinct from nullif(btrim(p_answer_text), '')
    or stored.repetitions is distinct from p_repetitions then
    raise exception 'attempt id was already used with different practice data' using errcode = '23505';
  end if;

  return next stored;
end;
$$;

revoke all on function public.record_speaking_practice(uuid, uuid, uuid, text, text, text, integer)
  from public, anon, authenticated;
grant execute on function public.record_speaking_practice(uuid, uuid, uuid, text, text, text, integer)
  to service_role;
